stages:
  preprocess_background:
    cmd: python src/data/remove_background.py --input data/raw --output 
      data/processed
    deps:
    - data/raw
    - src/data/remove_background.py
    outs:
    - data/processed
  split_data:
    cmd: python src/data/split_data.py --input data/processed --output 
      data/dataset_split
    deps:
    - data/processed
    - src/data/split_data.py
    params:
    - split
    outs:
    - data/dataset_split
  augment_train:
    cmd: python src/data/augment.py --input data/dataset_split/train --output 
      data/dataset_train_final --type pill
    deps:
    - data/dataset_split/train
    - src/data/augment.py
    params:
    - augment.pill
    outs:
    - data/dataset_train_final
  train_pill:
    cmd: python src/train.py --train_dir data/dataset_train_final --val_dir 
      data/dataset_split/val --output_dir experiments/arcface_lite_v1 --type 
      pill
    deps:
    - data/dataset_split/val
    - data/dataset_train_final
    - src/data/dataset.py
    - src/models/architecture.py
    - src/train.py
    params:
    - train.pill
    outs:
    - experiments/arcface_lite_v1/pill
  preprocess_box:
    cmd: python src/data/remove_background.py --input data/raw_box --output 
      data/processed_box
    deps:
    - data/raw_box
    - src/data/remove_background.py
    outs:
    - data/processed_box
  split_box:
    cmd: python src/data/split_data.py --input data/processed_box --output 
      data/dataset_split_box
    deps:
    - data/processed_box
    - src/data/split_data.py
    params:
    - split
    outs:
    - data/dataset_split_box
  augment_box:
    cmd: python src/data/augment.py --input data/dataset_split_box/train 
      --output data/dataset_train_final_box --type box
    deps:
    - data/dataset_split_box/train
    - src/data/augment.py
    params:
    - augment.box
    outs:
    - data/dataset_train_final_box
  train_box:
    cmd: python src/train.py --train_dir data/dataset_train_final_box --val_dir 
      data/dataset_split_box/val --output_dir experiments/arcface_lite_v1 --type
      box
    deps:
    - data/dataset_split_box/val
    - data/dataset_train_final_box
    - src/data/dataset.py
    - src/models/architecture.py
    - src/train.py
    params:
    - train.box
    outs:
    - experiments/arcface_lite_v1/box
