stages:
  # ---------------------------------------------------------
  # 💊 PIPELINE: PILL (เม็ดยา)
  # ---------------------------------------------------------
  preprocess_background: # (ชื่อเดิมของ pill preprocess)
    cmd: python src/data/remove_background.py --input data/raw --output data/processed
    deps:
    - data/raw
    - src/data/remove_background.py
    outs:
    - data/processed:
        persist: true

  split_data: # (ชื่อเดิมของ pill split)
    cmd: python src/data/split_data.py --input data/processed --output data/dataset_split
    deps:
    - data/processed
    - src/data/split_data.py
    params:
    - split
    outs:
    - data/dataset_split

  augment_train: # (ชื่อเดิมของ pill augment)
    cmd: python src/data/augment.py --input data/dataset_split/train --output data/dataset_train_final --type pill
    deps:
    - data/dataset_split/train
    - src/data/augment.py
    params:
    - augment.pill
    outs:
    - data/dataset_train_final

  train_pill:
    cmd: python src/train.py --train_dir data/dataset_train_final --val_dir data/dataset_split/val --output_dir experiments/arcface_lite_v1 --type pill
    deps:
    - data/dataset_split/val
    - data/dataset_train_final
    - src/data/dataset.py
    - src/models/architecture.py
    - src/train.py
    params:
    - train.pill
    outs:
    - experiments/arcface_lite_v1/pill

  # ---------------------------------------------------------
  # 📦 PIPELINE: BOX (กล่องยา)
  # ---------------------------------------------------------
  preprocess_box: # ✅ เก็บอันนี้ไว้ (มี persist: true)
    cmd: python src/data/remove_background.py --input data/raw_box --output data/processed_box
    deps:
    - data/raw_box
    - src/data/remove_background.py
    outs:
    - data/processed_box:
        persist: true 

  split_box:
    cmd: python src/data/split_data.py --input data/processed_box --output data/dataset_split_box
    deps:
    - data/processed_box
    - src/data/split_data.py
    params:
    - split
    outs:
    - data/dataset_split_box

  augment_box:
    cmd: python src/data/augment.py --input data/dataset_split_box/train --output data/dataset_train_final_box --type box
    deps:
    - data/dataset_split_box/train
    - src/data/augment.py
    params:
    - augment.box
    outs:
    - data/dataset_train_final_box

  train_box: # (Full Train)
    cmd: python src/train.py --train_dir data/dataset_train_final_box --val_dir data/dataset_split_box/val --output_dir experiments/arcface_lite_v1/box --type box
    deps:
    - data/dataset_split_box/val
    - data/dataset_train_final_box
    - src/data/dataset.py
    - src/models/architecture.py
    - src/train.py
    params:
    - train.box
    outs:
    - experiments/arcface_lite_v1/box

  finetune_box: # (Fast Update)
    cmd: python src/finetune.py --data_dir data/dataset_train_final_box --old_model_dir experiments/arcface_lite_v1/box --output_dir experiments/arcface_finetuned/box --type box
    deps:
    - data/dataset_train_final_box
    - experiments/arcface_lite_v1/box
    - src/finetune.py
    params:
    - train.box
    outs:
    - experiments/arcface_finetuned/box

  evaluate_box:
    cmd: python src/evaluate.py --test_dir data/dataset_split_box/test --model_dir experiments/arcface_finetuned/box --type box --threshold 70.0
    deps:
    - data/dataset_split_box/test
    - experiments/arcface_finetuned/box/best_model.pth
    - src/evaluate.py
    metrics:
    - experiments/arcface_finetuned/box/metrics.json:
        cache: false