stages:
  # ========================================================
  # 📦 BOX PIPELINE (กล่องยา)
  # ========================================================

# แก้ไขทุกจุดที่มี data/ ใน dvc.yaml ให้เป็นแบบนี้
  preprocess_box:
    cmd: python src/data/remove_background.py --input data/raw_box --output data/processed_box
    deps:
      - data/raw_box
      - src/data/remove_background.py
    outs:
      - data/processed_box:  # <--- ต้องมีเครื่องหมาย : ต่อท้าย path
          push: false        # <--- เคาะ Space เข้าไป 4 ครั้ง (หรือให้เยื้องเข้าไป)
  split_box:
    cmd: python src/data/split_data.py --input data/processed_box --output data/dataset_split_box
    deps:
    - data/processed_box
    - src/data/split_data.py
    params:
    - split
    outs:
    - data/dataset_split_box
    

  augment_box:
    cmd: python src/data/augment.py --input data/dataset_split_box/train --output data/dataset_train_final_box --type box
    deps:
    - data/dataset_split_box/train
    - src/data/augment.py
    params:
    - augment.box
    outs:
    - data/dataset_train_final_box

  # Base Model Training (Full Backbone) -> ผลลัพธ์อยู่ที่ arcface_lite_v1
  train_box:
    cmd: python src/train.py --train_dir data/dataset_train_final_box --val_dir data/dataset_split_box/val --output_dir experiments/arcface_lite_v1/box --type box
    deps:
    - data/dataset_train_final_box
    - data/dataset_split_box/val
    - src/train.py
    params:
    - train.box
    outs:
    - experiments/arcface_lite_v1/box

  # Incremental Learning (Head Finetuning) -> ผลลัพธ์อยู่ที่ arcface_finetuned
  finetune_box:
    cmd: python src/finetune.py --data_dir data/dataset_train_final_box --old_model_dir experiments/arcface_lite_v1/box --output_dir experiments/arcface_finetuned/box --type box
    deps:
    - data/dataset_train_final_box
    - experiments/arcface_lite_v1/box/best_model.pth
    - src/finetune.py
    params:
    - train.box
    outs:
    - experiments/arcface_finetuned/box

  # --------------------------------------------------------
  # ✅ EVALUATION STAGES (แยกเส้นทางชัดเจน)
  # --------------------------------------------------------

  # 1. สำหรับ Incremental Mode (เช็ค Finetuned Model)
  evaluate_box:
    cmd: python src/evaluate.py --test_dir data/dataset_split_box/test --model_dir experiments/arcface_finetuned/box --metrics_out metrics/box_metrics.json --type box --threshold 70.0
    deps:
    - data/dataset_split_box/test
    - experiments/arcface_finetuned/box/best_model.pth  # <--- ผูกกับ Finetune
    - src/evaluate.py
    metrics:
    - metrics/box_metrics.json:
        cache: false

  # 2. สำหรับ Major/Full Mode (เช็ค Base Model ตรงๆ) 🔥 เพิ่มใหม่!
  evaluate_base_box:
    cmd: python src/evaluate.py --test_dir data/dataset_split_box/test --model_dir experiments/arcface_lite_v1/box --metrics_out metrics/box_base_metrics.json --type box --threshold 70.0
    deps:
    - data/dataset_split_box/test
    - experiments/arcface_lite_v1/box/best_model.pth    # <--- ผูกกับ Base Model (ไม่เรียก Finetune)
    - src/evaluate.py
    metrics:
    - metrics/box_base_metrics.json:
        cache: false

  # ========================================================
  # 💊 PILL PIPELINE (Refactored: raw_pill & processed_pill)
  # ========================================================

  preprocess_pill:
    cmd: python src/data/remove_background.py --input data/raw_pill --output data/processed_pill
    deps:
    - data/raw_pill
    - src/data/remove_background.py
    outs:
    - data/processed_pill

  split_pill:
    cmd: python src/data/split_data.py --input data/processed_pill --output data/dataset_split_pill
    deps:
    - data/processed_pill
    - src/data/split_data.py
    params:
    - split
    outs:
    - data/dataset_split_pill

  augment_pill:
    cmd: python src/data/augment.py --input data/dataset_split_pill/train --output data/dataset_train_final_pill --type pill
    deps:
    - data/dataset_split_pill/train
    - src/data/augment.py
    params:
    - augment.pill
    outs:
    - data/dataset_train_final_pill

  # Base Model Training
  train_pill:
    cmd: python src/train.py --train_dir data/dataset_train_final_pill --val_dir data/dataset_split_pill/val --output_dir experiments/arcface_lite_v1/pill --type pill
    deps:
    - data/dataset_train_final_pill
    - data/dataset_split_pill/val
    - src/train.py
    params:
    - train.pill
    outs:
    - experiments/arcface_lite_v1/pill

  # Incremental Learning
  finetune_pill:
    cmd: python src/finetune.py --data_dir data/dataset_train_final_pill --old_model_dir experiments/arcface_lite_v1/pill --output_dir experiments/arcface_finetuned/pill --type pill
    deps:
    - data/dataset_train_final_pill
    - experiments/arcface_lite_v1/pill/best_model.pth
    - src/finetune.py
    params:
    - train.pill
    outs:
    - experiments/arcface_finetuned/pill

  # --------------------------------------------------------
  # ✅ EVALUATION STAGES (แยกเส้นทางชัดเจน)
  # --------------------------------------------------------

  # 1. สำหรับ Incremental Mode (เช็ค Finetuned Model)
  evaluate_pill:
    cmd: python src/evaluate.py --test_dir data/dataset_split_pill/test --model_dir experiments/arcface_finetuned/pill --metrics_out metrics/pill_metrics.json --type pill --threshold 20.0
    deps:
    - data/dataset_split_pill/test
    - experiments/arcface_finetuned/pill/best_model.pth # <--- ผูกกับ Finetune
    - src/evaluate.py
    metrics:
    - metrics/pill_metrics.json:
        cache: false

  # 2. สำหรับ Major/Full Mode (เช็ค Base Model ตรงๆ) 🔥 เพิ่มใหม่!
  evaluate_base_pill:
    cmd: python src/evaluate.py --test_dir data/dataset_split_pill/test --model_dir experiments/arcface_lite_v1/pill --metrics_out metrics/pill_base_metrics.json --type pill --threshold 20.0
    deps:
    - data/dataset_split_pill/test
    - experiments/arcface_lite_v1/pill/best_model.pth # <--- ผูกกับ Base Model
    - src/evaluate.py
    metrics:
    - metrics/pill_base_metrics.json:
        cache: false