# params.yaml

# ---------------------------------------------------------
# ✂️ SPLIT CONFIG
# ---------------------------------------------------------
split:
  val_ratio: 0.2    # ใช้สำหรับจูนระหว่างเทรน
  test_ratio: 0.1   # 🔥 ของใหม่: ใช้สำหรับตรวจก่อนขึ้น S3
  seed: 42
# ---------------------------------------------------------
# 🧪 AUGMENT CONFIG (Target per class)
# ---------------------------------------------------------
# params.yaml (Update ส่วน augment)

augment:
  # 💊 PILL: หมุนได้อิสระ กลับหัวได้
  pill:
    target_per_class: 300
    aug_params:
      rotate_limit: 180       # หมุนรอบทิศ
      p_rotate: 0.8
      p_vertical_flip: 0.5    # ✅ กลับหัวได้
      p_horizontal_flip: 0.5
      p_brightness: 0.2
      blur_limit: 3

  # 📦 BOX: ห้ามกลับหัว เอียงได้นิดเดียว
  box:
    target_per_class: 350 
    aug_params:
      rotate_limit: 15        # เอียงนิดเดียวพอ
      p_rotate: 0.5
      p_vertical_flip: 0.0    # ❌ ห้ามกลับหัว (Set เป็น 0)
      p_horizontal_flip: 0.5  # กลับซ้ายขวาได้
      p_brightness: 0.2
      shift_limit: 0.05
      scale_limit: 0.1
      perspective_scale: 0.1  # บิดภาพ 3D
# ---------------------------------------------------------
# 🚀 TRAIN CONFIG
# ---------------------------------------------------------
train:
  # 💊 Config สำหรับเม็ดยา (เน้นรายละเอียด, Model เล็ก)
  pill:
    model_name: "convnext_small"
    img_size: 512
    batch_size: 16
    epochs: 3        # เทรนจริงจังใช้ 15-20 รอบ
    lr: 0.00003
    weight_decay: 0.0001
    dropout: 0.3
    embed_dim: 512    # ขนาด Vector ของ ArcFace
    focal:
      gamma: 2.0
      alpha: 0.25
    seed: 42
    num_workers: 0    # Mac M1/M2 ต้องใช้ 0

  # 📦 Config สำหรับกล่องยา (ภาพรวมใหญ่, Model ใหญ่ขึ้น)
  box:
    model_name: "convnext_small" # หรือ "swin_base_patch4_window12_384"
    img_size: 384               # ✅ เพิ่มเพื่อให้เห็น Detail ตัวหนังสือ
    batch_size: 16              # ⚠️ ลดลงหน่อยเพราะเพิ่ม img_size (แลกความชัด)
    epochs: 10                  # ✅ ให้เวลาโมเดลได้เรียนรู้จริงๆ
    lr: 0.00003                 # ใช้ OneCycleLR Scheduler จะจึ้งมาก
    weight_decay: 0.05          # เพิ่มขึ้นนิดนึงกัน Overfit 
    dropout: 0.4                # กัน Overfit เพราะข้อมูล Fine-grained มักจำจด
    embed_dim: 512              # ขนาด Vector ของ ArcFace
    focal:
      gamma: 2.0                # ปรับให้ Standard ขึ้น
      alpha: 0.25
    num_workers: 8 