# params.yaml

# ---------------------------------------------------------
# ✂️ SPLIT CONFIG
# ---------------------------------------------------------
split:
  val_ratio: 0.2    # ใช้สำหรับจูนระหว่างเทรน
  test_ratio: 0.1   # 🔥 ของใหม่: ใช้สำหรับตรวจก่อนขึ้น S3
  seed: 42
# ---------------------------------------------------------
# 🧪 AUGMENT CONFIG (Target per class)
# ---------------------------------------------------------
# params.yaml (Update ส่วน augment)

augment:
  # 💊 PILL: หมุนได้อิสระ กลับหัวได้
  pill:
    target_per_class: 500
    aug_params:
      rotate_limit: 180       # หมุนรอบทิศ
      p_rotate: 0.8
      p_vertical_flip: 0.5    # ✅ กลับหัวได้
      p_horizontal_flip: 0.5
      p_brightness: 0.2
      blur_limit: 3

  # 📦 BOX: ห้ามกลับหัว เอียงได้นิดเดียว
  box:
    target_per_class: 50
    aug_params:
      rotate_limit: 15        # เอียงนิดเดียวพอ
      p_rotate: 0.5
      p_vertical_flip: 0.0    # ❌ ห้ามกลับหัว (Set เป็น 0)
      p_horizontal_flip: 0.5  # กลับซ้ายขวาได้
      p_brightness: 0.2
      shift_limit: 0.05
      scale_limit: 0.1
      perspective_scale: 0.1  # บิดภาพ 3D
# ---------------------------------------------------------
# 🚀 TRAIN CONFIG
# ---------------------------------------------------------
train:
  # 💊 Config สำหรับเม็ดยา (เน้นรายละเอียด, Model เล็ก)
  pill:
    model_name: "convnext_tiny"
    img_size: 224
    batch_size: 16
    epochs: 1        # เทรนจริงจังใช้ 15-20 รอบ
    lr: 0.0001
    weight_decay: 0.0001
    dropout: 0.3
    embed_dim: 512    # ขนาด Vector ของ ArcFace
    focal:
      gamma: 2.0
      alpha: 0.25
    seed: 42
    num_workers: 0    # Mac M1/M2 ต้องใช้ 0

  # 📦 Config สำหรับกล่องยา (ภาพรวมใหญ่, Model ใหญ่ขึ้น)
  box:
    model_name: "convnext_small"
    img_size: 224
    batch_size: 16    # ลด Batch ลงหน่อยเพราะ Model ใหญ่ เดี๋ยว RAM เต็ม
    epochs: 1        # เทรนนานกว่านิดนึงเพราะ Parameter เยอะ
    lr: 0.0001
    weight_decay: 0.0001
    dropout: 0.5      # เพิ่ม Dropout กัน Overfit
    embed_dim: 512
    focal:
      gamma: 2.0
      alpha: 0.25
    seed: 42
    num_workers: 0